# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import estoque_pb2 as estoque__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in estoque_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EstoqueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdicionaProduto = channel.unary_unary(
                '/EstoqueService/AdicionaProduto',
                request_serializer=estoque__pb2.ProdutoRequest.SerializeToString,
                response_deserializer=estoque__pb2.ProdutoId.FromString,
                _registered_method=True)
        self.AlteraQuantidadeDeProduto = channel.unary_unary(
                '/EstoqueService/AlteraQuantidadeDeProduto',
                request_serializer=estoque__pb2.AlteraQuantidadeRequest.SerializeToString,
                response_deserializer=estoque__pb2.StatusEstoque.FromString,
                _registered_method=True)
        self.ListaProdutos = channel.unary_unary(
                '/EstoqueService/ListaProdutos',
                request_serializer=estoque__pb2.EmptyRequest.SerializeToString,
                response_deserializer=estoque__pb2.ListaDeProdutos.FromString,
                _registered_method=True)
        self.FimDaExecucao = channel.unary_unary(
                '/EstoqueService/FimDaExecucao',
                request_serializer=estoque__pb2.EmptyRequest.SerializeToString,
                response_deserializer=estoque__pb2.StatusEstoque.FromString,
                _registered_method=True)


class EstoqueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AdicionaProduto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlteraQuantidadeDeProduto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListaProdutos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FimDaExecucao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstoqueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdicionaProduto': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionaProduto,
                    request_deserializer=estoque__pb2.ProdutoRequest.FromString,
                    response_serializer=estoque__pb2.ProdutoId.SerializeToString,
            ),
            'AlteraQuantidadeDeProduto': grpc.unary_unary_rpc_method_handler(
                    servicer.AlteraQuantidadeDeProduto,
                    request_deserializer=estoque__pb2.AlteraQuantidadeRequest.FromString,
                    response_serializer=estoque__pb2.StatusEstoque.SerializeToString,
            ),
            'ListaProdutos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListaProdutos,
                    request_deserializer=estoque__pb2.EmptyRequest.FromString,
                    response_serializer=estoque__pb2.ListaDeProdutos.SerializeToString,
            ),
            'FimDaExecucao': grpc.unary_unary_rpc_method_handler(
                    servicer.FimDaExecucao,
                    request_deserializer=estoque__pb2.EmptyRequest.FromString,
                    response_serializer=estoque__pb2.StatusEstoque.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EstoqueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EstoqueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EstoqueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AdicionaProduto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstoqueService/AdicionaProduto',
            estoque__pb2.ProdutoRequest.SerializeToString,
            estoque__pb2.ProdutoId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlteraQuantidadeDeProduto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstoqueService/AlteraQuantidadeDeProduto',
            estoque__pb2.AlteraQuantidadeRequest.SerializeToString,
            estoque__pb2.StatusEstoque.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListaProdutos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstoqueService/ListaProdutos',
            estoque__pb2.EmptyRequest.SerializeToString,
            estoque__pb2.ListaDeProdutos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FimDaExecucao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EstoqueService/FimDaExecucao',
            estoque__pb2.EmptyRequest.SerializeToString,
            estoque__pb2.StatusEstoque.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
