# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pedidos.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pedidos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpedidos.proto\"$\n\x0cListaDeItens\x12\x14\n\x05itens\x18\x01 \x03(\x0b\x32\x05.Item\"+\n\x04Item\x12\x0f\n\x07prod_id\x18\x01 \x01(\x05\x12\x12\n\nquantidade\x18\x02 \x01(\x05\"\x16\n\x08PedidoId\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\rListaIdStatus\x12\x16\n\x03par\x18\x01 \x03(\x0b\x32\t.IdStatus\"-\n\x08IdStatus\x12\x11\n\tpedido_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"C\n\x11\x46imExecucaoStatus\x12\x16\n\x0e\x65stoque_status\x18\x01 \x01(\x05\x12\x16\n\x0epedidos_ativos\x18\x02 \x01(\x05\"\x1f\n\rStatusPedidos\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\x96\x01\n\x0ePedidosService\x12+\n\nCriaPedido\x12\r.ListaDeItens\x1a\x0e.ListaIdStatus\x12*\n\rCancelaPedido\x12\t.PedidoId\x1a\x0e.StatusPedidos\x12+\n\rFimDaExecucao\x12\x06.Empty\x1a\x12.FimExecucaoStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedidos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTADEITENS']._serialized_start=17
  _globals['_LISTADEITENS']._serialized_end=53
  _globals['_ITEM']._serialized_start=55
  _globals['_ITEM']._serialized_end=98
  _globals['_PEDIDOID']._serialized_start=100
  _globals['_PEDIDOID']._serialized_end=122
  _globals['_LISTAIDSTATUS']._serialized_start=124
  _globals['_LISTAIDSTATUS']._serialized_end=163
  _globals['_IDSTATUS']._serialized_start=165
  _globals['_IDSTATUS']._serialized_end=210
  _globals['_FIMEXECUCAOSTATUS']._serialized_start=212
  _globals['_FIMEXECUCAOSTATUS']._serialized_end=279
  _globals['_STATUSPEDIDOS']._serialized_start=281
  _globals['_STATUSPEDIDOS']._serialized_end=312
  _globals['_EMPTY']._serialized_start=314
  _globals['_EMPTY']._serialized_end=321
  _globals['_PEDIDOSSERVICE']._serialized_start=324
  _globals['_PEDIDOSSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
