# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pedidos_pb2 as pedidos__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pedidos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PedidosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriaPedido = channel.unary_unary(
                '/PedidosService/CriaPedido',
                request_serializer=pedidos__pb2.ListaDeItens.SerializeToString,
                response_deserializer=pedidos__pb2.ListaIdStatus.FromString,
                _registered_method=True)
        self.CancelaPedido = channel.unary_unary(
                '/PedidosService/CancelaPedido',
                request_serializer=pedidos__pb2.PedidoId.SerializeToString,
                response_deserializer=pedidos__pb2.StatusPedidos.FromString,
                _registered_method=True)
        self.FimDaExecucao = channel.unary_unary(
                '/PedidosService/FimDaExecucao',
                request_serializer=pedidos__pb2.Empty.SerializeToString,
                response_deserializer=pedidos__pb2.FimExecucaoStatus.FromString,
                _registered_method=True)


class PedidosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriaPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelaPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FimDaExecucao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PedidosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriaPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.CriaPedido,
                    request_deserializer=pedidos__pb2.ListaDeItens.FromString,
                    response_serializer=pedidos__pb2.ListaIdStatus.SerializeToString,
            ),
            'CancelaPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelaPedido,
                    request_deserializer=pedidos__pb2.PedidoId.FromString,
                    response_serializer=pedidos__pb2.StatusPedidos.SerializeToString,
            ),
            'FimDaExecucao': grpc.unary_unary_rpc_method_handler(
                    servicer.FimDaExecucao,
                    request_deserializer=pedidos__pb2.Empty.FromString,
                    response_serializer=pedidos__pb2.FimExecucaoStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PedidosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PedidosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PedidosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriaPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PedidosService/CriaPedido',
            pedidos__pb2.ListaDeItens.SerializeToString,
            pedidos__pb2.ListaIdStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelaPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PedidosService/CancelaPedido',
            pedidos__pb2.PedidoId.SerializeToString,
            pedidos__pb2.StatusPedidos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FimDaExecucao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PedidosService/FimDaExecucao',
            pedidos__pb2.Empty.SerializeToString,
            pedidos__pb2.FimExecucaoStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
